### ISSUE TITLE
Crash WrappedRecipe 1.7.10

### ISSUE THREAD

**Issue by SvEgiiVEteR** [Elecs-Mods/CraftingTable-IV#20]
http://hastebin.com/giyofufuqi.coffee

**Comment by srs-bsns** [comment]
Also happening with CraftingTableIV-1.8.9-1.2.76

**Comment by Elec332** [comment]
@srs-bsns Could you try this with the latest version on CF? (build 77)

And when you crash again, post a fresh log?

**Comment by MisterShawn** [comment]
Loaded fine locally, but crashed on server: http://pastebin.com/HPyh1Tgm (Build 77 for 1.8.9)

**Comment by srs-bsns** [comment]
If I try to load CraftingTableIV-1.8.9-1.2.77 and ElecCore-1.8.9-1.4.209 with the same mods from the initial crash that I experienced, the server crashes with the stack trace below (I assume the crash is actually a mod interaction, but with the bug on your side.)
(List of loaded mods for the crash: https://gist.github.com/srs-bsns/7185d994efca3ea02d89)

```
[18:24:22] [Server thread/INFO]: Preparing spawn area: 75%
[18:24:23] [Server thread/INFO]: Preparing spawn area: 83%
[18:24:24] [Server thread/INFO]: Preparing spawn area: 92%
[18:24:26] [Server thread/ERROR]: Encountered an unexpected exception
java.lang.IllegalArgumentException
    at elec332.craftingtableiv.abstraction.handler.WrappedRecipe.of(WrappedRecipe.java:30) ~[WrappedRecipe.class:?]
    at elec332.craftingtableiv.abstraction.handler.CraftingHandler.handleRecipe(CraftingHandler.java:96) ~[CraftingHandler.class:?]
    at elec332.craftingtableiv.abstraction.handler.CraftingHandler.rebuildList(CraftingHandler.java:62) ~[CraftingHandler.class:?]
    at elec332.craftingtableiv.abstraction.CraftingTableIVAbstractionLayer.reloadRecipes(CraftingTableIVAbstractionLayer.java:77) ~[CraftingTableIVAbstractionLayer.class:?]
    at elec332.craftingtableiv.abstraction.CraftingTableIVAbstractionLayer.serverStarted(CraftingTableIVAbstractionLayer.java:72) ~[CraftingTableIVAbstractionLayer.class:?]
    at elec332.craftingtableiv.CraftingTableIV.serverStarted(CraftingTableIV.java:119) ~[CraftingTableIV.class:?]
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_65]
    at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_65]
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_65]
    at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_65]
    at net.minecraftforge.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:560) ~[forge-1.8.9-11.15.0.1692-universal.jar:?]
    at sun.reflect.GeneratedMethodAccessor4.invoke(Unknown Source) ~[?:?]
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_65]
    at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_65]
    at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74) ~[guava-17.0.jar:?]
    at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47) ~[guava-17.0.jar:?]
    at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322) ~[guava-17.0.jar:?]
    at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304) ~[guava-17.0.jar:?]
    at com.google.common.eventbus.EventBus.post(EventBus.java:275) ~[guava-17.0.jar:?]
    at net.minecraftforge.fml.common.LoadController.sendEventToModContainer(LoadController.java:211) ~[LoadController.class:?]
    at net.minecraftforge.fml.common.LoadController.propogateStateMessage(LoadController.java:189) ~[LoadController.class:?]
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_65]
    at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_65]
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_65]
    at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_65]
    at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74) ~[guava-17.0.jar:?]
    at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47) ~[guava-17.0.jar:?]
    at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322) ~[guava-17.0.jar:?]
    at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304) ~[guava-17.0.jar:?]
    at com.google.common.eventbus.EventBus.post(EventBus.java:275) ~[guava-17.0.jar:?]
    at net.minecraftforge.fml.common.LoadController.distributeStateMessage(LoadController.java:118) ~[LoadController.class:?]
    at net.minecraftforge.fml.common.Loader.serverStarted(Loader.java:792) ~[Loader.class:?]
    at net.minecraftforge.fml.common.FMLCommonHandler.handleServerStarted(FMLCommonHandler.java:288) ~[FMLCommonHandler.class:?]
    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:443) [MinecraftServer.class:?]
    at java.lang.Thread.run(Unknown Source) [?:1.8.0_65]
```

If I use just CraftingTableIV-1.8.9-1.2.77 and ElecCore-1.8.9-1.4.209 with no other mods, I can get into the world without the server crashing, but the rendering of water is broken:
![](http://www.nihilism.ca/minecraft/2016-01-10_18.42.59.png)

Hope this helps you. If you would like me to test anything else, just ask.

Full log files from server and client:
https://gist.githubusercontent.com/srs-bsns/d11567b40c77fe5817cd/raw/64b4f0b1502950fd51d0b30ace9a39e65cd15168/CT4-issue20-server.log
https://gist.githubusercontent.com/srs-bsns/d11567b40c77fe5817cd/raw/64b4f0b1502950fd51d0b30ace9a39e65cd15168/CT4-issue20-client.log

**Comment by Elec332** [comment]
Thanks @srs-bsns, That log confirmed my thoughts, fixing it now.
I'll also look into that weird stuff with water, no idea why that's happening.

**Comment by Elec332** [comment]
Thanks a lot for the help.
If you notice this line: "Recipe XXX has invalid ingredients!", please report them here, I might be able to add compat for them.

**Comment by srs-bsns** [comment]
First, the unrelated rendering issue with your core is fixed, but I'm still getting this same crash for CraftingTable-IV.
(Same stacktrace with new line numbers for posterity:)

```
java.lang.IllegalArgumentException
    at elec332.craftingtableiv.abstraction.handler.WrappedRecipe.of(WrappedRecipe.java:30)
    at elec332.craftingtableiv.abstraction.handler.CraftingHandler.handleRecipe(CraftingHandler.java:107)
    at elec332.craftingtableiv.abstraction.handler.CraftingHandler.rebuildList(CraftingHandler.java:64)
    at elec332.craftingtableiv.abstraction.CraftingTableIVAbstractionLayer.reloadRecipes(CraftingTableIVAbstractionLayer.java:77)
    at elec332.craftingtableiv.abstraction.CraftingTableIVAbstractionLayer.serverStarted(CraftingTableIVAbstractionLayer.java:72)
    at elec332.craftingtableiv.CraftingTableIV.serverStarted(CraftingTableIV.java:119)
```

Knowing that no crash was occuring using the mod on it's own, I knew there had to be some kind of mod interaction involved, so I started to disable mods a few at a time until it stopped crashing and discovered that it's Tinkers' Construct. I can reproduce the crash everytime with only:
ElecCore-1.8.9-1.4.210
CraftingTableIV-1.8.9-1.2.79
Mantle-1.8.9-0.6.jenkins69
TConstruct-1.8.9-2.0.1.jenkins38

I think they might be doing some funky new stuff with Tinkers' tools in normal crafting tables now (part swapping, etc..) which could have strange recipes being registered which are messing with your mod, but I haven't been paying any attention, really. Also, it's very incomplete ATM. But, you may still want to get into contact with them to figure out what's going on if you can't find the issue.

Cheers.

**Comment by srs-bsns** [comment]
I just happened to be on CurseForge when you uploaded build 81. Here's the client log for you, though I'm sure you already have your own by now:
https://gist.github.com/srs-bsns/a4dfa0c49dab4c1865a4

**Comment by Elec332** [comment]
@srs-bsns Thank you very much for all the debugging. Build 81 was indeed a hotfix for a different, but in a crashlog similar looking crash. I will get in touch with the tCon devs and ask what/why they are doing this weird recipe stuff. I also made sure that if other mods start doing weird stuff with the recipes, CraftingTable-IV will not crash and simply skip the recipe.

**Comment by draknyte1** [comment]
Not using tCon myself. 1.7.10 latest version of CTIV.
http://pastebin.com/Rs5sHtv6

I do however have GregTech which I imagine does 'unique' recipe registering.
Though, it was launching fine prior to me updating ElecCore and CraftingTableIV. Recipes just weren't crafting though.

**Comment by quentfr21** [comment]
same for me but i don't have greg tech
xD
