### ISSUE TITLE
Crash with latest versions

### ISSUE THREAD

**Issue by kwiknik** [Elecs-Mods/CraftingTable-IV#26]
I'm using latest version of this and ElecCore:

```
CraftingTableIV-1.8.9-1.2.84.jar
ElecCore-1.8.9-1.4.224.jar
```

Have installed these to my Forge server. Using latest version of Forge with latest stable MC server there.

I can create the CTIV just fine, and place it. I can also see craftables in it. But when I try to take an item (I tried a comparator) I get this crash:

```
---- Minecraft Crash Report ----

WARNING: coremods are present:
  BetterFoliageLoader (BetterFoliage-MC1.8.x-2.0.2.jar)
  FMLPlugin (InventoryTweaks-1.60-dev-27.jar)
Contact their authors BEFORE contacting forge

// Quite honestly, I wouldn't worry myself about that.

Time: 2/13/16 4:14 PM
Description: Updating screen events

java.lang.NoSuchMethodError: elec332.craftingtableiv.tileentity.TileEntityCraftingTableIV.myLocation()Lelec332/core/util/BlockLoc;
    at elec332.craftingtableiv.abstraction.handler.CraftingHandler$CraftingTableIVHandler.writeToNBT(CraftingHandler.java:359)
    at elec332.craftingtableiv.abstraction.CraftingTableIVAbstractionLayer.sendCraftingMessage(CraftingTableIVAbstractionLayer.java:120)
    at elec332.craftingtableiv.abstraction.handler.CraftingHandler.sendCraftingMessage(CraftingHandler.java:332)
    at elec332.craftingtableiv.abstraction.handler.CraftingHandler.canCraft(CraftingHandler.java:212)
    at elec332.craftingtableiv.abstraction.handler.CraftingHandler.canCraft(CraftingHandler.java:134)
    at elec332.craftingtableiv.blocks.container.GuiCTableIV.onRequestSingleRecipeOutput(GuiCTableIV.java:145)
    at elec332.craftingtableiv.blocks.container.GuiCTableIV.func_146984_a(GuiCTableIV.java:134)
    at net.minecraft.client.gui.inventory.GuiContainer.func_73864_a(GuiContainer.java:388)
    at elec332.craftingtableiv.blocks.container.GuiCTableIV.func_73864_a(GuiCTableIV.java:238)
    at net.minecraft.client.gui.GuiScreen.func_146274_d(GuiScreen.java:554)
    at elec332.craftingtableiv.blocks.container.GuiCTableIV.func_146274_d(GuiCTableIV.java:372)
    at net.minecraft.client.gui.GuiScreen.func_146269_k(GuiScreen.java:523)
    at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:1674)
    at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1024)
    at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:349)
    at net.minecraft.client.main.Main.main(SourceFile:124)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:497)
    at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
    at net.minecraft.launchwrapper.Launch.main(Launch.java:28)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Stacktrace:
    at elec332.craftingtableiv.abstraction.handler.CraftingHandler$CraftingTableIVHandler.writeToNBT(CraftingHandler.java:359)
    at elec332.craftingtableiv.abstraction.CraftingTableIVAbstractionLayer.sendCraftingMessage(CraftingTableIVAbstractionLayer.java:120)
    at elec332.craftingtableiv.abstraction.handler.CraftingHandler.sendCraftingMessage(CraftingHandler.java:332)
    at elec332.craftingtableiv.abstraction.handler.CraftingHandler.canCraft(CraftingHandler.java:212)
    at elec332.craftingtableiv.abstraction.handler.CraftingHandler.canCraft(CraftingHandler.java:134)
    at elec332.craftingtableiv.blocks.container.GuiCTableIV.onRequestSingleRecipeOutput(GuiCTableIV.java:145)
    at elec332.craftingtableiv.blocks.container.GuiCTableIV.func_146984_a(GuiCTableIV.java:134)
    at net.minecraft.client.gui.inventory.GuiContainer.func_73864_a(GuiContainer.java:388)
    at elec332.craftingtableiv.blocks.container.GuiCTableIV.func_73864_a(GuiCTableIV.java:238)
    at net.minecraft.client.gui.GuiScreen.func_146274_d(GuiScreen.java:554)
    at elec332.craftingtableiv.blocks.container.GuiCTableIV.func_146274_d(GuiCTableIV.java:372)
    at net.minecraft.client.gui.GuiScreen.func_146269_k(GuiScreen.java:523)

-- Affected screen --
Details:
    Screen name: elec332.craftingtableiv.blocks.container.GuiCTableIV

-- Affected level --
Details:
    Level name: MpServer
    All players: 1 total; [EntityPlayerSP['kwiknik'/79813, l='MpServer', x=-569.58, y=200.50, z=803.52]]
    Chunk stats: MultiplayerChunkCache: 169, 169
    Level seed: 0
    Level generator: ID 00 - default, ver 1. Features enabled: false
    Level generator options: 
    Level spawn location: -102.00,64.00,244.00 - World: (-102,64,244), Chunk: (at 10,4,4 in -7,15; contains blocks -112,0,240 to -97,255,255), Region: (-1,0; contains chunks -32,0 to -1,31, blocks -512,0,0 to -1,255,511)
    Level time: 11412286 game time, 1119397 day time
    Level dimension: 0
    Level storage version: 0x00000 - Unknown?
    Level weather: Rain time: 0 (now: false), thunder time: 0 (now: false)
    Level game mode: Game mode: survival (ID 0). Hardcore: false. Cheats: false
    Forced entities: 35 total; [EntityPlayerSP['kwiknik'/79813, l='MpServer', x=-569.58, y=200.50, z=803.52], EntityPig['Pig'/85248, l='MpServer', x=-494.88, y=66.00, z=729.06], EntityMinecartChest['container.minecart'/85251, l='MpServer', x=-579.50, y=39.06, z=871.50], EntityRabbit['Rabbit'/85279, l='MpServer', x=-559.81, y=63.00, z=842.94], EntityChicken['Chicken'/85278, l='MpServer', x=-546.91, y=62.56, z=835.00], EntityMinecartChest['container.minecart'/85281, l='MpServer', x=-614.50, y=36.00, z=778.47], EntityRabbit['Rabbit'/85287, l='MpServer', x=-547.75, y=63.28, z=838.94], EntityMinecartChest['container.minecart'/85161, l='MpServer', x=-584.50, y=45.06, z=827.50], EntityPig['Pig'/85289, l='MpServer', x=-570.25, y=63.00, z=775.53], EntityMinecartChest['container.minecart'/85160, l='MpServer', x=-583.50, y=41.06, z=823.50], EntityMinecartChest['container.minecart'/85288, l='MpServer', x=-572.50, y=35.06, z=781.50], EntityPig['Pig'/85290, l='MpServer', x=-562.09, y=63.00, z=769.97], EntityMinecartChest['container.minecart'/85292, l='MpServer', x=-606.50, y=36.00, z=772.84], EntityOtherPlayerMP['penuts9090'/42928, l='MpServer', x=-73.72, y=63.00, z=272.69], EntityHorse['Horse'/85171, l='MpServer', x=-570.53, y=63.00, z=857.00], EntityRabbit['Rabbit'/85303, l='MpServer', x=-493.84, y=65.31, z=802.19], EntityMinecartChest['container.minecart'/85174, l='MpServer', x=-601.50, y=41.06, z=799.88], EntityRabbit['Rabbit'/85302, l='MpServer', x=-569.00, y=63.00, z=785.19], EntityChicken['Chicken'/85305, l='MpServer', x=-566.13, y=205.00, z=797.09], EntityMinecartChest['container.minecart'/85304, l='MpServer', x=-563.50, y=40.00, z=796.94], EntityChicken['Chicken'/85307, l='MpServer', x=-566.91, y=205.00, z=797.88], EntityChicken['Chicken'/85306, l='MpServer', x=-566.13, y=205.00, z=797.88], EntityChicken['Chicken'/85309, l='MpServer', x=-566.91, y=205.00, z=797.09], EntityChicken['Chicken'/85308, l='MpServer', x=-566.25, y=204.63, z=797.72], EntityCow['Cow'/85183, l='MpServer', x=-527.72, y=70.00, z=860.22], EntityMinecartChest['container.minecart'/85182, l='MpServer', x=-566.50, y=40.06, z=800.50], EntityChicken['Chicken'/85310, l='MpServer', x=-566.69, y=204.63, z=797.22], EntityHorse['Horse'/85203, l='MpServer', x=-565.00, y=68.00, z=872.03], EntityPig['Pig'/85209, l='MpServer', x=-561.09, y=63.00, z=755.47], EntityPig['Pig'/85208, l='MpServer', x=-561.16, y=63.00, z=754.28], EntityHorse['Horse'/85223, l='MpServer', x=-503.44, y=73.00, z=866.59], EntityHorse['Horse'/85222, l='MpServer', x=-534.25, y=69.00, z=866.91], EntityOtherPlayerMP['morris231089'/57114, l='MpServer', x=359.38, y=85.00, z=1071.25], EntityPig['Pig'/85230, l='MpServer', x=-492.22, y=65.00, z=832.16], EntityMinecartChest['container.minecart'/85243, l='MpServer', x=-576.50, y=35.06, z=773.50]]
    Retry entities: 0 total; []
    Server brand: fml,forge
    Server type: Non-integrated multiplayer server
Stacktrace:
    at net.minecraft.client.multiplayer.WorldClient.func_72914_a(WorldClient.java:404)
    at net.minecraft.client.Minecraft.func_71396_d(Minecraft.java:2536)
    at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:370)
    at net.minecraft.client.main.Main.main(SourceFile:124)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:497)
    at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
    at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

-- System Details --
Details:
    Minecraft Version: 1.8.9
    Operating System: Linux (amd64) version 4.1.0-0.steamos.24-amd64
    CPU: 4x Intel(R) Core(TM)2 Quad CPU Q8200 @ 2.33GHz
    Java Version: 1.8.0_66, Oracle Corporation
    Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
    Memory: 166247176 bytes (158 MB) / 646873088 bytes (616 MB) up to 1060372480 bytes (1011 MB)
    JVM Flags: 5 total; -Xmx1G -XX:+UseConcMarkSweepGC -XX:+CMSIncrementalMode -XX:-UseAdaptiveSizePolicy -Xmn128M
    IntCache: cache: 0, tcache: 0, allocated: 13, tallocated: 95
    FML: MCP 9.19 Powered by Forge 11.15.1.1726 Optifine OptiFine_1.8.9_HD_U_H2 9 mods loaded, 9 mods active
    States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
    UCHIJA  mcp{9.19} [Minecraft Coder Pack] (minecraft.jar) 
    UCHIJA  FML{8.0.99.99} [Forge Mod Loader] (forge-1.8.9-11.15.1.1726.jar) 
    UCHIJA  Forge{11.15.1.1726} [Minecraft Forge] (forge-1.8.9-11.15.1.1726.jar) 
    UCHIJA  BetterFoliage{2.0.2} [Better Foliage] (BetterFoliage-MC1.8.x-2.0.2.jar) 
    UCHIJA  ElecCore{1.4.224} [ElecCore] (ElecCore-1.8.9-1.4.224.jar) 
    UCHIJA  CraftingTableIV{1.2.84} [CraftingTableIV] (CraftingTableIV-1.8.9-1.2.84.jar) 
    UCHIJA  inventorytweaks{1.60-dev-27-43ecdd2} [Inventory Tweaks] (InventoryTweaks-1.60-dev-27.jar) 
    UCHIJA  journeymap{5.1.3} [JourneyMap] (journeymap-1.8.8-5.1.3-unlimited.jar) 
    UCHIJA  soundfilters{0.8_for_1.8} [Sound Filters] (SoundFilters-0.8_for_1.8.jar) 
    Loaded coremods (and transformers): 
BetterFoliageLoader (BetterFoliage-MC1.8.x-2.0.2.jar)
  mods.betterfoliage.loader.BetterFoliageTransformer
FMLPlugin (InventoryTweaks-1.60-dev-27.jar)
  invtweaks.forge.asm.ContainerTransformer
    GL info: ' Vendor: 'NVIDIA Corporation' Version: '4.5.0 NVIDIA 352.55' Renderer: 'GeForce GTX 560 Ti/PCIe/SSE2'
    Launched Version: 1.8.9-forge1.8.9-11.15.1.1726
    LWJGL: 2.9.4
    OpenGL: GeForce GTX 560 Ti/PCIe/SSE2 GL version 4.5.0 NVIDIA 352.55, NVIDIA Corporation
    GL Caps: Using GL 1.3 multitexturing.
Using GL 1.3 texture combiners.
Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
Shaders are available because OpenGL 2.1 is supported.
VBOs are available because OpenGL 1.5 is supported.

    Using VBOs: Yes
    Is Modded: Definitely; Client brand changed to 'fml,forge'
    Type: Client (map_client.txt)
    Resource Packs: Pixel Perfection V3.3.zip, Pixel Daydreams (vB.3).zip
    Current Language: English (US)
    Profiler Position: N/A (disabled)
    CPU: 4x Intel(R) Core(TM)2 Quad CPU Q8200 @ 2.33GHz
```

**Comment by kwiknik** [comment]
I've tried with the new build of ElecCore you posted about 12 hours ago - same issue.

I've tested on both Debian Wheezy and Windows 10, it makes no difference.

**Comment by Elec332** [comment]
Yes, the problem here is that you are using a too-new version of ElecCore, Ill upload a fix soon :)

**Comment by kwiknik** [comment]
Ah you're a star for telling me, thank you very much Elec :) i'll try an older version when I get home tonight.

I saw you'd committed recently saying there was a fix for this, but I guess it happened more than once hehe :) I write code for a living so know how it goes.

Thank you sincerely for making this awesome mod, it's a pleasure to find the best implementation of a kind of mod is also up to date :D Your efforts are much appreciated!
