### ISSUE TITLE
Can't even make the crafting table...

### ISSUE THREAD

**Issue by Paradox** [Elecs-Mods/CraftingTable-IV#29]
Every time I try to make the table, by placing a crafting table and a book, in either inventory crafting, or, another crafting table, it freezes and crashes the client... I even tried switching to creative mode, so I could just grab a table from there, and, as soon as i moused over the CTIV, it froze and crashed...

Crash log:

---- Minecraft Crash Report ----
// Why did you do that?

Time: 4/15/16 5:42 PM
Description: Rendering item

java.lang.IllegalStateException: Already building!
    at net.minecraft.client.renderer.WorldRenderer.func_181668_a(WorldRenderer.java:184)
    at net.minecraft.client.model.TexturedQuad.func_178765_a(TexturedQuad.java:59)
    at net.minecraft.client.model.ModelBox.func_178780_a(ModelBox.java:88)
    at net.minecraft.client.model.ModelRenderer.func_78788_d(ModelRenderer.java:280)
    at net.minecraft.client.model.ModelRenderer.func_78785_a(ModelRenderer.java:120)
    at elec332.craftingtableiv.client.ModelCraftingTableIV.func_78088_a(ModelCraftingTableIV.java:73)
    at elec332.craftingtableiv.client.CraftingTableIVRenderer.renderTileEntityAt(CraftingTableIVRenderer.java:37)
    at elec332.craftingtableiv.client.CraftingTableIVRenderer.func_180535_a(CraftingTableIVRenderer.java:12)
    at elec332.core.client.model.model.TESRItemModel.renderTesr(TESRItemModel.java:61)
    at elec332.core.client.model.model.TESRItemModel.func_177550_a(TESRItemModel.java:48)
    at net.minecraft.client.renderer.entity.RenderItem.func_175045_a(RenderItem.java:130)
    at net.minecraft.client.renderer.entity.RenderItem.func_175036_a(RenderItem.java:111)
    at net.minecraft.client.renderer.entity.RenderItem.func_180454_a(RenderItem.java:152)
    at net.minecraft.client.renderer.entity.RenderItem.func_175042_a(RenderItem.java:356)
    at net.minecraft.client.renderer.entity.RenderItem.func_180450_b(RenderItem.java:395)
    at net.minecraft.client.gui.inventory.GuiContainer.func_146977_a(GuiContainer.java:265)
    at net.minecraft.client.gui.inventory.GuiContainer.func_73863_a(GuiContainer.java:95)
    at net.minecraft.client.renderer.InventoryEffectRenderer.func_73863_a(InventoryEffectRenderer.java:49)
    at net.minecraft.client.gui.inventory.GuiInventory.func_73863_a(SourceFile:47)
    at net.minecraftforge.client.ForgeHooksClient.drawScreen(ForgeHooksClient.java:311)
    at net.minecraft.client.renderer.EntityRenderer.func_181560_a(EntityRenderer.java:1104)
    at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1051)
    at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:349)
    at net.minecraft.client.main.Main.main(SourceFile:124)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
    at java.lang.reflect.Method.invoke(Unknown Source)
    at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
    at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
## A detailed walkthrough of the error, its code path and all known details is as follows:

-- Head --
Stacktrace:
    at net.minecraft.client.renderer.WorldRenderer.func_181668_a(WorldRenderer.java:184)
    at net.minecraft.client.model.TexturedQuad.func_178765_a(TexturedQuad.java:59)
    at net.minecraft.client.model.ModelBox.func_178780_a(ModelBox.java:88)
    at net.minecraft.client.model.ModelRenderer.func_78788_d(ModelRenderer.java:280)
    at net.minecraft.client.model.ModelRenderer.func_78785_a(ModelRenderer.java:120)
    at elec332.craftingtableiv.client.ModelCraftingTableIV.func_78088_a(ModelCraftingTableIV.java:73)
    at elec332.craftingtableiv.client.CraftingTableIVRenderer.renderTileEntityAt(CraftingTableIVRenderer.java:37)
    at elec332.craftingtableiv.client.CraftingTableIVRenderer.func_180535_a(CraftingTableIVRenderer.java:12)
    at elec332.core.client.model.model.TESRItemModel.renderTesr(TESRItemModel.java:61)
    at elec332.core.client.model.model.TESRItemModel.func_177550_a(TESRItemModel.java:48)
    at net.minecraft.client.renderer.entity.RenderItem.func_175045_a(RenderItem.java:130)
    at net.minecraft.client.renderer.entity.RenderItem.func_175036_a(RenderItem.java:111)
    at net.minecraft.client.renderer.entity.RenderItem.func_180454_a(RenderItem.java:152)
    at net.minecraft.client.renderer.entity.RenderItem.func_175042_a(RenderItem.java:356)

-- Item being rendered --
Details:
    Item Type: net.minecraft.item.ItemBlock@75922191
    Item Aux: 0
    Item NBT: null
    Item Foil: false
Stacktrace:
    at net.minecraft.client.renderer.entity.RenderItem.func_180450_b(RenderItem.java:395)
    at net.minecraft.client.gui.inventory.GuiContainer.func_146977_a(GuiContainer.java:265)
    at net.minecraft.client.gui.inventory.GuiContainer.func_73863_a(GuiContainer.java:95)
    at net.minecraft.client.renderer.InventoryEffectRenderer.func_73863_a(InventoryEffectRenderer.java:49)
    at net.minecraft.client.gui.inventory.GuiInventory.func_73863_a(SourceFile:47)
    at net.minecraftforge.client.ForgeHooksClient.drawScreen(ForgeHooksClient.java:311)

-- Screen render details --
Details:
    Screen name: net.minecraft.client.gui.inventory.GuiInventory
    Mouse location: Scaled: (504, 223). Absolute: (1008, 611)
    Screen size: Scaled: (960, 529). Absolute: (1920, 1057). Scale factor of 2

-- Affected level --
Details:
    Level name: MpServer
    All players: 1 total; [EntityPlayerSP['Paradox'/465, l='MpServer', x=129.81, y=64.00, z=263.74]]
    Chunk stats: MultiplayerChunkCache: 441, 441
    Level seed: 0
    Level generator: ID 00 - default, ver 1. Features enabled: false
    Level generator options: 
    Level spawn location: 204.00,64.00,240.00 - World: (204,64,240), Chunk: (at 12,4,0 in 12,15; contains blocks 192,0,240 to 207,255,255), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
    Level time: 740690 game time, 806763 day time
    Level dimension: 0
    Level storage version: 0x00000 - Unknown?
    Level weather: Rain time: 0 (now: false), thunder time: 0 (now: false)
    Level game mode: Game mode: survival (ID 0). Hardcore: false. Cheats: false
    Forced entities: 80 total; [EntityCreeper['Creeper'/59396, l='MpServer', x=91.72, y=20.00, z=231.13], EntityItem['item.item.dyePowder.black'/39691, l='MpServer', x=151.88, y=41.00, z=273.50], EntityBat['Bat'/62738, l='MpServer', x=60.59, y=29.16, z=215.41], EntityBat['Bat'/59923, l='MpServer', x=68.21, y=28.45, z=263.30], EntitySpider['Spider'/60438, l='MpServer', x=190.50, y=70.00, z=324.50], EntityCow['Cow'/25, l='MpServer', x=53.84, y=67.00, z=278.06], EntityZombie['Zombie'/53020, l='MpServer', x=85.03, y=31.00, z=193.44], EntitySkeleton['Skeleton'/56349, l='MpServer', x=142.50, y=70.00, z=343.50], EntityChicken['Chicken'/40, l='MpServer', x=55.41, y=69.00, z=189.31], EntityChicken['Chicken'/41, l='MpServer', x=56.38, y=69.00, z=190.50], EntityCow['Cow'/46, l='MpServer', x=58.84, y=80.00, z=234.94], EntityZombie['Zombie'/50222, l='MpServer', x=106.91, y=47.00, z=281.59], EntityBat['Bat'/52271, l='MpServer', x=114.66, y=23.10, z=193.31], EntityCow['Cow'/48, l='MpServer', x=61.06, y=81.00, z=249.25], EntityItem['item.item.dyePowder.black'/39985, l='MpServer', x=138.13, y=45.00, z=289.97], EntityZombie['Zombie'/59953, l='MpServer', x=158.34, y=46.00, z=273.34], EntityCow['Cow'/52, l='MpServer', x=62.91, y=79.00, z=264.97], EntityCow['Cow'/54, l='MpServer', x=53.53, y=84.00, z=264.69], EntityCow['Cow'/56, l='MpServer', x=54.75, y=73.00, z=285.78], EntityCow['Cow'/57, l='MpServer', x=53.69, y=67.00, z=279.22], EntityCow['Cow'/58, l='MpServer', x=52.03, y=69.00, z=272.16], EntitySkeleton['Skeleton'/59964, l='MpServer', x=194.50, y=69.00, z=321.50], EntitySkeleton['Skeleton'/49982, l='MpServer', x=99.50, y=22.00, z=196.50], EntitySpider['Spider'/60223, l='MpServer', x=54.50, y=68.00, z=263.50], EntityZombie['Zombie'/60479, l='MpServer', x=117.31, y=72.00, z=207.88], EntityZombie['Zombie'/57154, l='MpServer', x=63.50, y=13.00, z=300.50], EntityCow['Cow'/70, l='MpServer', x=68.44, y=78.00, z=249.34], EntityCow['Cow'/71, l='MpServer', x=69.97, y=78.00, z=252.13], EntityCow['Cow'/73, l='MpServer', x=76.97, y=75.00, z=260.13], EntitySquid['Squid'/57930, l='MpServer', x=190.88, y=62.00, z=267.75], EntityItem['item.item.egg'/58442, l='MpServer', x=88.31, y=71.00, z=319.91], EntitySpider['Spider'/58190, l='MpServer', x=54.50, y=69.00, z=260.50], EntityZombie['Zombie'/62542, l='MpServer', x=136.50, y=74.00, z=186.50], EntityEnderman['Enderman'/52560, l='MpServer', x=132.50, y=19.00, z=287.50], EntityCreeper['Creeper'/58963, l='MpServer', x=104.97, y=49.00, z=265.50], EntitySkeleton['Skeleton'/61011, l='MpServer', x=74.50, y=42.00, z=324.50], EntityCreeper['Creeper'/61012, l='MpServer', x=141.50, y=12.00, z=277.50], EntityCow['Cow'/86, l='MpServer', x=84.06, y=74.00, z=244.13], EntityZombie['Zombie'/61014, l='MpServer', x=124.88, y=71.00, z=202.50], EntitySkeleton['Skeleton'/62294, l='MpServer', x=91.50, y=74.00, z=223.78], EntityZombie['Zombie'/61015, l='MpServer', x=165.50, y=65.00, z=311.50], EntityCow['Cow'/88, l='MpServer', x=83.28, y=67.00, z=316.44], EntityChicken['Chicken'/90, l='MpServer', x=88.28, y=71.00, z=320.47], EntityItem['item.item.dyePowder.black'/54618, l='MpServer', x=75.75, y=28.00, z=265.13], EntityZombie['Zombie'/61278, l='MpServer', x=174.50, y=75.00, z=195.50], EntityZombie['Zombie'/61279, l='MpServer', x=106.88, y=24.00, z=203.66], EntitySpider['Spider'/58976, l='MpServer', x=109.03, y=71.00, z=234.41], EntityCow['Cow'/99, l='MpServer', x=102.16, y=64.00, z=312.13], EntitySkeleton['Skeleton'/62307, l='MpServer', x=60.50, y=69.00, z=188.50], EntitySkeleton['Skeleton'/62309, l='MpServer', x=80.50, y=68.00, z=334.50], EntityChicken['Chicken'/109, l='MpServer', x=115.63, y=70.00, z=335.44], EntityCreeper['Creeper'/60785, l='MpServer', x=158.50, y=43.00, z=260.50], EntityItem['item.item.dyePowder.black'/38272, l='MpServer', x=154.56, y=40.00, z=273.63], EntityBat['Bat'/59787, l='MpServer', x=102.56, y=48.94, z=330.66], EntityBat['Bat'/146, l='MpServer', x=139.50, y=54.44, z=291.34], EntityBat['Bat'/62104, l='MpServer', x=145.88, y=42.06, z=341.97], EntitySkeleton['Skeleton'/52643, l='MpServer', x=113.06, y=47.00, z=277.53], EntityCow['Cow'/166, l='MpServer', x=173.97, y=77.00, z=191.44], EntityBat['Bat'/59563, l='MpServer', x=118.13, y=21.09, z=207.63], EntityChicken['Chicken'/172, l='MpServer', x=176.31, y=70.00, z=337.66], EntityBat['Bat'/61106, l='MpServer', x=62.63, y=37.16, z=317.91], EntityCreeper['Creeper'/53173, l='MpServer', x=210.50, y=29.00, z=283.50], EntityBat['Bat'/58296, l='MpServer', x=203.47, y=33.02, z=184.07], EntityCreeper['Creeper'/59321, l='MpServer', x=73.50, y=71.00, z=219.50], EntityChicken['Chicken'/186, l='MpServer', x=178.50, y=70.00, z=340.34], EntitySpider['Spider'/60868, l='MpServer', x=184.50, y=69.00, z=324.50], EntitySkeleton['Skeleton'/59847, l='MpServer', x=71.38, y=76.00, z=255.88], EntityChicken['Chicken'/204, l='MpServer', x=205.50, y=80.00, z=201.47], EntityChicken['Chicken'/207, l='MpServer', x=203.97, y=62.66, z=277.97], EntityChicken['Chicken'/208, l='MpServer', x=198.25, y=62.72, z=274.59], EntityZombie['Zombie'/55764, l='MpServer', x=134.50, y=14.00, z=290.50], EntityPlayerSP['Paradox'/465, l='MpServer', x=129.81, y=64.00, z=263.74], EntityZombie['Zombie'/61659, l='MpServer', x=78.56, y=70.00, z=322.84], EntityChicken['Chicken'/223, l='MpServer', x=211.34, y=62.63, z=260.81], EntitySkeleton['Skeleton'/51426, l='MpServer', x=158.50, y=20.00, z=212.50], EntityChicken['Chicken'/227, l='MpServer', x=210.13, y=65.00, z=300.44], EntityBat['Bat'/58097, l='MpServer', x=97.53, y=28.10, z=187.75], EntityZombie['Zombie'/59379, l='MpServer', x=166.81, y=64.00, z=221.69], EntitySkeleton['Skeleton'/55543, l='MpServer', x=179.50, y=69.00, z=326.50], EntityCreeper['Creeper'/59386, l='MpServer', x=103.72, y=71.00, z=232.91]]
    Retry entities: 0 total; []
    Server brand: fml,forge
    Server type: Integrated singleplayer server
Stacktrace:
    at net.minecraft.client.multiplayer.WorldClient.func_72914_a(WorldClient.java:347)
    at net.minecraft.client.Minecraft.func_71396_d(Minecraft.java:2536)
    at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:370)
    at net.minecraft.client.main.Main.main(SourceFile:124)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
    at java.lang.reflect.Method.invoke(Unknown Source)
    at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
    at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

-- System Details --
Details:
    Minecraft Version: 1.8.9
    Operating System: Windows 10 (amd64) version 10.0
    Java Version: 1.8.0_77, Oracle Corporation
    Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
    Memory: 93045696 bytes (88 MB) / 566120448 bytes (539 MB) up to 1060372480 bytes (1011 MB)
    JVM Flags: 6 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx1G -XX:+UseConcMarkSweepGC -XX:+CMSIncrementalMode -XX:-UseAdaptiveSizePolicy -Xmn128M
    IntCache: cache: 0, tcache: 0, allocated: 12, tallocated: 94
    FML: MCP 9.19 Powered by Forge 11.15.1.1855 6 mods loaded, 6 mods active
    States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
    UCHIJAAAA   mcp{9.19} [Minecraft Coder Pack](minecraft.jar) 
    UCHIJAAAA   FML{8.0.99.99} [Forge Mod Loader](forge-1.8.9-11.15.1.1855.jar) 
    UCHIJAAAA   Forge{11.15.1.1855} [Minecraft Forge](forge-1.8.9-11.15.1.1855.jar) 
    UCHIJAAAA   ElecCore{1.4.247} [ElecCore](ElecCore-1.8.9-1.4.247.jar) 
    UCHIJAAAA   CraftingTableIV{1.2.84} [CraftingTableIV](CraftingTableIV-1.8.9-1.2.84.jar) 
    UCHIJAAAA   JoypadSplitscreenMod{1.8.9-0.21} [Joypad / SplitScreen Mod](JoypadMod-1.8.9-11.15.1.1722.jar) 
    Loaded coremods (and transformers): 
    GL info: ' Vendor: 'ATI Technologies Inc.' Version: '4.5.13416 Compatibility Profile Context 15.300.1025.1001' Renderer: 'AMD Radeon R7 Graphics + R7 240 Dual Graphics'
    Launched Version: 1.8.9-forge1.8.9-11.15.1.1855
    LWJGL: 2.9.4
    OpenGL: AMD Radeon R7 Graphics + R7 240 Dual Graphics GL version 4.5.13416 Compatibility Profile Context 15.300.1025.1001, ATI Technologies Inc.
    GL Caps: Using GL 1.3 multitexturing.
Using GL 1.3 texture combiners.
Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
Shaders are available because OpenGL 2.1 is supported.
VBOs are available because OpenGL 1.5 is supported.

```
Using VBOs: No
Is Modded: Definitely; Client brand changed to 'fml,forge'
Type: Client (map_client.txt)
Resource Packs: 
Current Language: English (US)
Profiler Position: N/A (disabled)
CPU: 4x AMD A10-7800 Radeon R7, 12 Compute Cores 4C+8G 
```

**Comment by Paradox** [comment]
Just wanted to add, I tried the 1.7.10 version, and, it works just fine, but, 1.8.9 doesn't.
