### ISSUE TITLE
Empty Crafting GUI

### ISSUE THREAD

**Issue by Zemogiter** [Elecs-Mods/CraftingTable-IV#42]
Just started to use this mod after some time and found a bug. The GUI where you click on blocks/items to craft is empty. Changing the depth of recursive search or version of the mod dosen't help. Here is the error log from OpenEye:

java.lang.UnsupportedOperationException: 

    at java.util.AbstractList.remove(-1)
    at java.util.AbstractList$Itr.remove(-1)
    at java.util.AbstractList.removeRange(-1)
    at java.util.AbstractList.clear(-1)
    at elec332.core.util.MinecraftList.clear(MinecraftList.java:62)
    at elec332.core.util.InventoryHelper.readItemsFromNBT(InventoryHelper.java:25)
    at elec332.core.util.BasicInventory.readFromNBT(BasicInventory.java:181)
    at elec332.craftingtableiv.tileentity.TileEntityCraftingTableIV.func_145839_a(TileEntityCraftingTableIV.java:63)
    at net.minecraft.tileentity.TileEntity.func_190200_a(TileEntity.java:123)
    at net.minecraft.world.chunk.storage.AnvilChunkLoader.loadEntities(AnvilChunkLoader.java:486)
    at net.minecraftforge.common.chunkio.ChunkIOProvider.syncCallback(ChunkIOProvider.java:96)
    at net.minecraftforge.common.chunkio.ChunkIOExecutor.syncChunkLoad(ChunkIOExecutor.java:94)
    at net.minecraft.world.gen.ChunkProviderServer.loadChunk(ChunkProviderServer.java:115)
    at net.minecraft.world.gen.ChunkProviderServer.func_186028_c(ChunkProviderServer.java:86)
    at net.minecraft.world.gen.ChunkProviderServer.func_186025_d(ChunkProviderServer.java:132)
    at net.minecraft.server.MinecraftServer.func_71222_d(MinecraftServer.java:298)
    at net.minecraft.server.integrated.IntegratedServer.func_71247_a(IntegratedServer.java:174)
    at net.minecraft.server.integrated.IntegratedServer.func_71197_b(IntegratedServer.java:197)
    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:431)
    at java.lang.Thread.run(-1)

I'm using ElecCore 1.6.360 and CraftingTableVI 1.3.108 which are the latest versions compatible with minecraft 1.10.2 at this moment.

**Comment by Elec332** [comment]
Hmmmm

**Comment by Samuel-James** [comment]
i have the same issue with the latest version. the crafting grid gui is empty.

**Comment by Elec332** [comment]
try clicking a random slot
