### ISSUE TITLE
No error or crash, the mod just isn't loaded.

### ISSUE THREAD

**Issue by harleypig** [Elecs-Mods/CraftingTable-IV#44]
Game play is apparently unaffected, but the mod is not listed in the mod list.

Relevant portion of `fml-client-latest.log`:
```
*[15:25:25] [Client thread/DEBUG] [FML/]: Examining file CraftingTableIV-1.11-1.3.108.jar for potential mods
*[15:25:25] [Client thread/TRACE] [FML/]: Located mcmod.info file in file CraftingTableIV-1.11-1.3.108.jar
*[15:25:25] [Client thread/DEBUG] [FML/]: Identified a mod of type Lnet/minecraftforge/fml/common/Mod; (elec332.craftingtableiv.CraftingTableIV) - loading
 [15:25:25] [Client thread/WARN] [FML/]: ****************************************
*[15:25:25] [Client thread/WARN] [FML/]: * The modid CraftingTableIV is not the same as it's lowercase version. Lowercasing is enforced in 1.11
 [15:25:25] [Client thread/WARN] [FML/]: *  at net.minecraftforge.fml.common.FMLModContainer.sanityCheckModId(FMLModContainer.java:143)
 [15:25:25] [Client thread/WARN] [FML/]: *  at net.minecraftforge.fml.common.FMLModContainer.<init>(FMLModContainer.java:126)
 [15:25:25] [Client thread/WARN] [FML/]: *  at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
 [15:25:25] [Client thread/WARN] [FML/]: *  at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
 [15:25:25] [Client thread/WARN] [FML/]: *  at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
 [15:25:25] [Client thread/WARN] [FML/]: *  at java.lang.reflect.Constructor.newInstance(Constructor.java:423)...
 [15:25:25] [Client thread/WARN] [FML/]: ****************************************
 [15:25:25] [Client thread/ERROR] [FML/]: Unable to construct net.minecraftforge.fml.common.Mod container
 java.lang.reflect.InvocationTargetException
   at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:1.8.0_111]
   at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62) ~[?:1.8.0_111]
   at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[?:1.8.0_111]
   at java.lang.reflect.Constructor.newInstance(Constructor.java:423) ~[?:1.8.0_111]
   at net.minecraftforge.fml.common.ModContainerFactory.build(ModContainerFactory.java:86) [ModContainerFactory.class:?]
   at net.minecraftforge.fml.common.discovery.JarDiscoverer.discover(JarDiscoverer.java:87) [JarDiscoverer.class:?]
   at net.minecraftforge.fml.common.discovery.ContainerType.findMods(ContainerType.java:49) [ContainerType.class:?]
   at net.minecraftforge.fml.common.discovery.ModCandidate.explore(ModCandidate.java:78) [ModCandidate.class:?]
   at net.minecraftforge.fml.common.discovery.ModDiscoverer.identifyMods(ModDiscoverer.java:141) [ModDiscoverer.class:?]
   at net.minecraftforge.fml.common.Loader.identifyMods(Loader.java:382) [Loader.class:?]
   at net.minecraftforge.fml.common.Loader.loadMods(Loader.java:522) [Loader.class:?]
   at net.minecraftforge.fml.client.FMLClientHandler.beginMinecraftLoading(FMLClientHandler.java:225) [FMLClientHandler.class:?]
   at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:438) [beq.class:?]
   at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:350) [beq.class:?]
   at net.minecraft.client.main.Main.main(SourceFile:124) [Main.class:?]
   at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_111]
   at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_111]
   at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_111]
   at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_111]
   at net.minecraft.launchwrapper.Launch.launch(Launch.java:135) [launchwrapper-1.12.jar:?]
   at net.minecraft.launchwrapper.Launch.main(Launch.java:28) [launchwrapper-1.12.jar:?]
*Caused by: java.lang.IllegalArgumentException: The modid CraftingTableIV is not the same as it's lowercase version. Lowercasing will be enforced in 1.11
   at net.minecraftforge.fml.common.FMLModContainer.sanityCheckModId(FMLModContainer.java:144) ~[FMLModContainer.class:?]
   at net.minecraftforge.fml.common.FMLModContainer.<init>(FMLModContainer.java:126) ~[FMLModContainer.class:?]
   ... 21 more
```

**Comment by harleypig** [comment]
Sorry, forgot to include some details:

Linux Mint 18
java-8-openjdk
Forge Mod Loader version 13.19.1.2189 for Minecraft 1.11

**Comment by SilentChaos512** [comment]
Recent Forge versions reject mods that have uppercase letters in the mod ID. The mod ID needs to be lowercased.

**Comment by Elec332** [comment]
Please update to the latest version

**Comment by SilentChaos512** [comment]
Is the latest build not 108? That's the most recent one I see.

**Comment by harleypig** [comment]
The latest on CurseForge is CraftingTableIV-1.11-1.3.108.jar. Is there another, or official, location to download jar files from?
