### ISSUE TITLE
Crash when place/opening the table: InvocationTargetException at  elec332.core.util.BasicItemHandler.(BasicItemHandler.java:21)

### ISSUE THREAD

**Issue by Lothrazar** [Elecs-Mods/CraftingTable-IV#57]
[20:59:11] [Server thread/INFO]: [Lothrazar: Set own game mode to Creative Mode]
[20:59:11] [Client thread/INFO]: [CHAT] Your game mode has been updated to Creative Mode
[20:59:23] [Client thread/INFO]: [STDERR]: java.lang.reflect.InvocationTargetException
[20:59:23] [Client thread/INFO]: [STDERR]: 	at sun.reflect.GeneratedMethodAccessor30.invoke(Unknown Source)
[20:59:23] [Client thread/INFO]: [STDERR]: 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[20:59:23] [Client thread/INFO]: [STDERR]: 	at java.lang.reflect.Method.invoke(Method.java:483)
[20:59:23] [Client thread/INFO]: [STDERR]: 	at Reflector.callInt(Reflector.java:741)
[20:59:23] [Client thread/INFO]: [STDERR]: 	at net.minecraft.block.state.BlockStateContainer$StateImplementation.getLightOpacity(BlockStateContainer.java:508)
[20:59:23] [Client thread/INFO]: [STDERR]: 	at net.minecraft.world.chunk.Chunk.func_177436_a(Chunk.java:589)
[20:59:23] [Client thread/INFO]: [STDERR]: 	at net.minecraft.world.World.func_180501_a(World.java:335)
[20:59:23] [Client thread/INFO]: [STDERR]: 	at net.minecraft.client.multiplayer.WorldClient.func_180501_a(WorldClient.java:647)
[20:59:23] [Client thread/INFO]: [STDERR]: 	at net.minecraft.item.ItemBlock.placeBlockAt(ItemBlock.java:170)
[20:59:23] [Client thread/INFO]: [STDERR]: 	at net.minecraft.item.ItemBlock.func_180614_a(ItemBlock.java:51)
[20:59:23] [Client thread/INFO]: [STDERR]: 	at net.minecraft.item.ItemStack.func_179546_a(ItemStack.java:166)
[20:59:23] [Client thread/INFO]: [STDERR]: 	at net.minecraft.client.multiplayer.PlayerControllerMP.func_187099_a(PlayerControllerMP.java:452)
[20:59:23] [Client thread/INFO]: [STDERR]: 	at PlayerControllerOF.func_187099_a(PlayerControllerOF.java:87)
[20:59:23] [Client thread/INFO]: [STDERR]: 	at net.minecraft.client.Minecraft.func_147121_ag(Minecraft.java:1521)
[20:59:23] [Client thread/INFO]: [STDERR]: 	at net.minecraft.client.Minecraft.func_184117_aA(Minecraft.java:2179)
[20:59:23] [Client thread/INFO]: [STDERR]: 	at net.minecraft.client.Minecraft.func_184118_az(Minecraft.java:1956)
[20:59:23] [Client thread/INFO]: [STDERR]: 	at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:1744)
[20:59:23] [Client thread/INFO]: [STDERR]: 	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1056)
[20:59:23] [Client thread/INFO]: [STDERR]: 	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:372)
[20:59:23] [Client thread/INFO]: [STDERR]: 	at net.minecraft.client.main.Main.main(SourceFile:124)
[20:59:23] [Client thread/INFO]: [STDERR]: 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[20:59:23] [Client thread/INFO]: [STDERR]: 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[20:59:23] [Client thread/INFO]: [STDERR]: 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[20:59:23] [Client thread/INFO]: [STDERR]: 	at java.lang.reflect.Method.invoke(Method.java:483)
[20:59:23] [Client thread/INFO]: [STDERR]: 	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
[20:59:23] [Client thread/INFO]: [STDERR]: 	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
[20:59:23] [Client thread/INFO]: [STDERR]: Caused by: java.lang.VerifyError: get long/double overflows locals
Exception Details:
  Location:
    elec332/core/util/InventoryHelper.wrapSlot(Lnet/minecraft/inventory/Slot;)Lelec332/core/inventory/widget/slot/WidgetSlot; @4: dload_3
  Reason:
    Local index 3 is invalid
  Bytecode:
    0x0000000: bb00 0f59 2901 2ab6 0015 2ab4 0019 2ab4
    0x0000010: 001c 2ab7 001f b0                      

[20:59:23] [Client thread/INFO]: [STDERR]: 	at elec332.core.util.BasicItemHandler.<init>(BasicItemHandler.java:21)
[20:59:23] [Client thread/INFO]: [STDERR]: 	at elec332.craftingtableiv.tileentity.TileEntityCraftingTableIV.<init>(TileEntityCraftingTableIV.java:31)
[20:59:23] [Client thread/INFO]: [STDERR]: 	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
[20:59:23] [Client thread/INFO]: [STDERR]: 	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
[20:59:23] [Client thread/INFO]: [STDERR]: 	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
[20:59:23] [Client thread/INFO]: [STDERR]: 	at java.lang.reflect.Constructor.newInstance(Constructor.java:408)
[20:59:23] [Client thread/INFO]: [STDERR]: 	at java.lang.Class.newInstance(Class.java:438)
[20:59:23] [Client thread/INFO]: [STDERR]: 	at elec332.core.tile.BlockTileBase.createTile(BlockTileBase.java:107)
[20:59:23] [Client thread/INFO]: [STDERR]: 	at elec332.core.tile.BlockTileBase.func_149915_a(BlockTileBase.java:100)
[20:59:23] [Client thread/INFO]: [STDERR]: 	at net.minecraft.block.Block.createTileEntity(Block.java:1223)
[20:59:23] [Client thread/INFO]: [STDERR]: 	at net.minecraft.world.chunk.Chunk.func_177422_i(Chunk.java:766)
[20:59:23] [Client thread/INFO]: [STDERR]: 	at net.minecraft.world.chunk.Chunk.func_177424_a(Chunk.java:784)
[20:59:23] [Client thread/INFO]: [STDERR]: 	at net.minecraft.world.World.func_175625_s(World.java:2355)
[20:59:23] [Client thread/INFO]: [STDERR]: 	at elec332.core.world.WorldHelper.getTileAt(WorldHelper.java:192)
[20:59:23] [Client thread/INFO]: [STDERR]: 	at elec332.core.tile.BlockTileBase.getLightOpacity(BlockTileBase.java:176)
[20:59:23] [Client thread/INFO]: [STDERR]: 	... 26 more
[20:59:24] [Client thread/INFO]: Saving gamerules of dimension 0 (MpServer) to config
[20:59:24] [Client thread/INFO]: Mapping halted in C:\Users\Sam\Documents\Curse\Minecraft\Instances\OPNC2.0\journeymap\data\sp\Copy of Seed 2!!!\DIM0
[20:59:24] [Server thread/INFO]: [STDOUT]: Server is stopping... force saving all loaded CosmeticArmor data.
[20:59:24] [Server thread/INFO]: [STDOUT]: 8364925c-2b2f-4391-b74c-a933e32c5e9f

**Comment by Elec332** [comment]
Fixed by latest ElecCore
