### ISSUE TITLE
(CRASH) Placed CTIV vanishes when broken, does not drop / return block.

### ISSUE THREAD

**Issue by Vaygrim** [Elecs-Mods/CraftingTable-IV#62]
Placing a CraftingTable IV then trying to break it with an Axe results in the below error message appearing on the Server console:

```
19:27:37] [Server thread/FATAL]: Error executing task
java.util.concurrent.ExecutionException: java.lang.NullPointerException
	at java.util.concurrent.FutureTask.report(FutureTask.java:122) ~[?:1.8.0_60]
	at java.util.concurrent.FutureTask.get(FutureTask.java:192) ~[?:1.8.0_60]
	at net.minecraft.util.Util.func_181617_a(SourceFile:46) [h.class:?]
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:668) [MinecraftServer.class:?]
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:387) [ld.class:?]
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:613) [MinecraftServer.class:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:471) [MinecraftServer.class:?]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_60]
Caused by: java.lang.NullPointerException
	at net.minecraft.entity.item.EntityItem.<init>(EntityItem.java:66) ~[yk.class:?]
	at elec332.core.world.WorldHelper.dropStack(WorldHelper.java:158) ~[WorldHelper.class:?]
	at elec332.core.world.WorldHelper.dropStack(WorldHelper.java:149) ~[WorldHelper.class:?]
	at elec332.core.world.WorldHelper.dropInventoryItems(WorldHelper.java:143) ~[WorldHelper.class:?]
	at elec332.craftingtableiv.blocks.BlockCraftingTableIV.func_180663_b(BlockCraftingTableIV.java:47) ~[BlockCraftingTableIV.class:?]
	at net.minecraft.world.chunk.Chunk.func_177436_a(Chunk.java:565) ~[asv.class:?]
	at net.minecraft.world.World.func_180501_a(World.java:331) ~[aid.class:?]
	at net.minecraft.block.Block.removedByPlayer(Block.java:1109) ~[akf.class:?]
	at net.minecraft.server.management.PlayerInteractionManager.removeBlock(PlayerInteractionManager.java:275) ~[lv.class:?]
	at net.minecraft.server.management.PlayerInteractionManager.func_180237_b(PlayerInteractionManager.java:333) ~[lv.class:?]
	at net.minecraft.server.management.PlayerInteractionManager.func_180785_a(PlayerInteractionManager.java:248) ~[lv.class:?]
	at net.minecraft.network.NetHandlerPlayServer.func_147345_a(NetHandlerPlayServer.java:642) ~[me.class:?]
	at net.minecraft.network.play.client.CPacketPlayerDigging.func_148833_a(SourceFile:40) ~[ja.class:?]
	at net.minecraft.network.play.client.CPacketPlayerDigging.func_148833_a(SourceFile:10) ~[ja.class:?]
	at net.minecraft.network.PacketThreadUtil$1.run(SourceFile:13) ~[fl$1.class:?]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) ~[?:1.8.0_60]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) ~[?:1.8.0_60]
	at net.minecraft.util.Util.func_181617_a(SourceFile:45) ~[h.class:?]
	... 5 more
```
Block shows a 'broken texture' texture when it breaks, and never actually drops. Just vanishes. Not critical, but very annoying.

**Comment by Vaygrim** [comment]
Correction, this has resulted in crashing the server at least once when the crafting table was broken.
[https://github.com/Vaygrim/CoopLife/issues/6](https://github.com/Vaygrim/CoopLife/issues/6)

**Comment by Vaygrim** [comment]
This issue has been closed for a week now. Is there an ETA on when the fix for it will be pushed out?

**Comment by Vaygrim** [comment]
@Elec332 It has been 2 weeks. Do you have time to push a fix out for this please?
