### ISSUE TITLE
1.12.2 Crash

### ISSUE THREAD

**Issue by FireController1847** [Elecs-Mods/CraftingTable-IV#73]
Mod Version -> CraftingTableIV-1.4.113.jar
Elec Version -> ElecCore1.12-1.8.430

This happens without all of the other mods I have as well. (I've tried it independantly)
```
---- Minecraft Crash Report ----

WARNING: coremods are present:
  Inventory Tweaks Coremod (InventoryTweaks-1.63.jar)
Contact their authors BEFORE contacting forge

// Sorry :(

Time: 11/6/17 10:59 PM
Description: There was a severe problem during mod loading that has caused the game to fail

net.minecraftforge.fml.common.LoaderExceptionModCrash: Caught exception from CraftingTable-IV (craftingtableiv)
Caused by: java.lang.NoClassDefFoundError: net/minecraftforge/fml/common/registry/IForgeRegistryEntry
	at java.lang.Class.forName0(Native Method)
	at java.lang.Class.forName(Class.java:344)
	at net.minecraftforge.fml.common.FMLModContainer.constructMod(FMLModContainer.java:522)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91)
	at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150)
	at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76)
	at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399)
	at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71)
	at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116)
	at com.google.common.eventbus.EventBus.post(EventBus.java:217)
	at net.minecraftforge.fml.common.LoadController.sendEventToModContainer(LoadController.java:253)
	at net.minecraftforge.fml.common.LoadController.propogateStateMessage(LoadController.java:231)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91)
	at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150)
	at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76)
	at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399)
	at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71)
	at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116)
	at com.google.common.eventbus.EventBus.post(EventBus.java:217)
	at net.minecraftforge.fml.common.LoadController.distributeStateMessage(LoadController.java:148)
	at net.minecraftforge.fml.common.Loader.loadMods(Loader.java:568)
	at net.minecraftforge.fml.client.FMLClientHandler.beginMinecraftLoading(FMLClientHandler.java:231)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:466)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:377)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
Caused by: java.lang.ClassNotFoundException: net.minecraftforge.fml.common.registry.IForgeRegistryEntry
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:191)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 39 more
Caused by: java.lang.NullPointerException
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:182)
	... 41 more


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
Details:
	Minecraft Version: 1.12.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_25, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 505083072 bytes (481 MB) / 1409286144 bytes (1344 MB) up to 15032385536 bytes (14336 MB)
	LiteLoader Brand: LiteLoader startup incomplete
	LiteLoader Mods: LiteLoader startup incomplete
	LaunchWrapper: 26 active transformer(s)
          - Transformer: net.minecraftforge.fml.common.asm.transformers.PatchingTransformer
          - Transformer: $wrapper.net.minecraftforge.fml.common.asm.transformers.BlamingTransformer
          - Transformer: $wrapper.net.minecraftforge.fml.common.asm.transformers.SideTransformer
          - Transformer: $wrapper.net.minecraftforge.fml.common.asm.transformers.EventSubscriptionTransformer
          - Transformer: $wrapper.net.minecraftforge.fml.common.asm.transformers.EventSubscriberTransformer
          - Transformer: org.spongepowered.asm.mixin.transformer.Proxy
          - Transformer: com.mumfrey.liteloader.transformers.event.EventProxyTransformer
          - Transformer: com.mumfrey.liteloader.launch.LiteLoaderTransformer
          - Transformer: com.mumfrey.liteloader.client.transformers.CrashReportTransformer
          - Transformer: net.minecraftforge.fml.common.asm.transformers.DeobfuscationTransformer
          - Transformer: net.minecraftforge.fml.common.asm.transformers.AccessTransformer
          - Transformer: invtweaks.forge.asm.ITAccessTransformer
          - Transformer: net.minecraftforge.fml.common.asm.transformers.ModAccessTransformer
          - Transformer: net.minecraftforge.fml.common.asm.transformers.ItemStackTransformer
          - Transformer: net.minecraftforge.fml.common.asm.transformers.ItemBlockTransformer
          - Transformer: net.minecraftforge.fml.common.asm.transformers.ItemBlockSpecialTransformer
          - Transformer: $wrapper.invtweaks.forge.asm.ContainerTransformer
          - Transformer: org.spongepowered.asm.mixin.transformer.Proxy
          - Transformer: net.minecraftforge.fml.common.asm.transformers.TerminalTransformer
          - Transformer: org.spongepowered.asm.mixin.transformer.Proxy
          - Transformer: com.mumfrey.liteloader.transformers.event.EventTransformer
          - Transformer: com.mumfrey.liteloader.common.transformers.LiteLoaderPacketTransformer
          - Transformer: com.mumfrey.liteloader.transformers.event.json.ModEventInjectionTransformer
          - Transformer: org.spongepowered.asm.mixin.transformer.Proxy
          - Transformer: net.minecraftforge.fml.common.asm.transformers.ModAPITransformer
          - Transformer: elec332.core.asm.ASMLoader
	JVM Flags: 8 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx14G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=16M
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP 9.42 Powered by Forge 14.23.0.2531 20 mods loaded, 20 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored

	| State | ID                | Version                  | Source                                      | Signature                                |
	|:----- |:----------------- |:------------------------ |:------------------------------------------- |:---------------------------------------- |
	| UC    | minecraft         | 1.12.2                   | minecraft.jar                               | None                                     |
	| UC    | mcp               | 9.42                     | minecraft.jar                               | None                                     |
	| UC    | FML               | 8.0.99.99                | forge-1.12.2-14.23.0.2531.jar               | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| UC    | forge             | 14.23.0.2531             | forge-1.12.2-14.23.0.2531.jar               | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| UC    | mercurius_updater | 1.0                      | MercuriusUpdater-1.12.2.jar                 | None                                     |
	| UC    | battletowers      | 1.6.1                    | BattleTowers-1.12.2.jar                     | None                                     |
	| UC    | bibliocraft       | 2.4.3                    | BiblioCraft[v2.4.3][MC1.12.0].jar           | None                                     |
	| UC    | eleccore          | 1.8.430                  | ElecCore-1.12-1.8.430.jar                   | None                                     |
	| UE    | craftingtableiv   | 1.0                      | CraftingTableIV-1.4.113.jar                 | None                                     |
	| UC    | customspawner     | 3.11.3                   | CustomMobSpawner-3.11.3.jar                 | None                                     |
	| UC    | mocreatures       | 12.0.3                   | DrZharks MoCreatures Mod-12.0.3.jar         | None                                     |
	| UC    | grapplemod        | 1.12-v10                 | grapplemod-1.12-v10.jar                     | None                                     |
	| UC    | lunatriuscore     | 1.2.0.42                 | LunatriusCore-1.12.2-1.2.0.42-universal.jar | None                                     |
	| UC    | ingameinfoxml     | 2.8.2.94                 | InGameInfoXML-1.12.2-2.8.2.94-universal.jar | None                                     |
	| UC    | inventorytweaks   | 1.63+release.109.220f184 | InventoryTweaks-1.63.jar                    | 55d2cd4f5f0961410bf7b91ef6c6bf00a766dcbe |
	| UC    | minecolonies      | 1.12.2-0.8.4596          | minecolonies-universal-1.12.2-0.8.4596.jar  | None                                     |
	| UC    | minions           | 2.0.2                    | Minions-1.12.2.jar                          | None                                     |
	| UC    | reforged          | 0.7.5                    | Reforged-0.7.5-1.12+.jar                    | None                                     |
	| UC    | roguelike         | 1.8.0                    | RoguelikeDungeons-1.12.2-1.8.0.jar          | None                                     |
	| UC    | vc                | 5.0.10                   | ViesCraft-1.12.2-5.0.10.jar                 | None                                     |

	Loaded coremods (and transformers): 
Inventory Tweaks Coremod (InventoryTweaks-1.63.jar)
  invtweaks.forge.asm.ContainerTransformer
	GL info: ' Vendor: 'NVIDIA Corporation' Version: '4.5.0 NVIDIA 385.69' Renderer: 'GeForce GTX 960/PCIe/SSE2'
```

**Comment by FireController1847** [comment]
@Elec332 Any ideas?

**Comment by Jkosio23** [comment]
the mod isn't updated to 1.12

**Comment by Elec332** [comment]
That version was not for 1.12, but for 1.10/1.11
A 1.12 version can be found on CF
