### ISSUE TITLE
[1.12.2] Crash on renderTooltip, with any mod that modifies it.

### ISSUE THREAD

**Issue by vakkendwarf** [Elecs-Mods/CraftingTable-IV#77]
The mod crashes when any other mod tries to modify the tooltip, here's two excerpts from when I try to display Thaumcraft's Aspects with shift, or when I use Immersive Engineering.

Please note that the "meeting point" of the crash between two mods is **always**:
>	at elec332.core.inventory.tooltip.ToolTip.renderTooltip(ToolTip.java:55)

Here's the two excerpts:

> java.lang.NullPointerException: Rendering screen
	at blusunrize.immersiveengineering.client.ClientEventHandler.onRenderTooltip(ClientEventHandler.java:266)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_861_ClientEventHandler_onRenderTooltip_PostText.invoke(.dynamic)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:182)
	at net.minecraftforge.fml.client.config.GuiUtils.drawHoveringText(GuiUtils.java:409)
	at elec332.core.inventory.tooltip.ToolTip.renderTooltip(ToolTip.java:55)
	at elec332.core.inventory.window.Window.drawScreenPost(Window.java:419)
	at elec332.craftingtableiv.inventory.WindowCraftingTableIV.drawScreenPost(WindowCraftingTableIV.java:414)
	at elec332.core.inventory.window.WindowGui.func_73863_a(WindowGui.java:98)
	at net.minecraftforge.client.ForgeHooksClient.drawScreen(ForgeHooksClient.java:396)
	at net.minecraft.client.renderer.EntityRenderer.func_181560_a(EntityRenderer.java:1124)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1119)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:398)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

And the second one:

>java.lang.NullPointerException: Rendering screen
	at thaumcraft.common.lib.crafting.ThaumcraftCraftingManager.getObjectTags(ThaumcraftCraftingManager.java:149)
	at thaumcraft.common.lib.crafting.ThaumcraftCraftingManager.getObjectTags(ThaumcraftCraftingManager.java:143)
	at thaumcraft.client.lib.events.HudHandler.renderAspectsInGui(HudHandler.java:794)
	at thaumcraft.client.lib.events.RenderEventHandler.tooltipEvent(RenderEventHandler.java:370)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_134_RenderEventHandler_tooltipEvent_PostBackground.invoke(.dynamic)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:182)
	at net.minecraftforge.fml.client.config.GuiUtils.drawHoveringText(GuiUtils.java:393)
	at elec332.core.inventory.tooltip.ToolTip.renderTooltip(ToolTip.java:55)
	at elec332.core.inventory.window.Window.drawScreenPost(Window.java:419)
	at elec332.craftingtableiv.inventory.WindowCraftingTableIV.drawScreenPost(WindowCraftingTableIV.java:414)
	at elec332.core.inventory.window.WindowGui.func_73863_a(WindowGui.java:98)
	at net.minecraftforge.client.ForgeHooksClient.drawScreen(ForgeHooksClient.java:396)
	at net.minecraft.client.renderer.EntityRenderer.func_181560_a(EntityRenderer.java:1124)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1119)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:398)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

**Comment by vitalexbel** [comment]
same with buildcraft

```
java.lang.NullPointerException: Rendering screen
	at buildcraft.builders.item.ItemSnapshot.getHeader(ItemSnapshot.java:56)
	at buildcraft.builders.BCBuildersEventDist.onRenderTooltipPostText(BCBuildersEventDist.java:97)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_643_BCBuildersEventDist_onRenderTooltipPostText_PostText.invoke(.dynamic)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:182)
	at net.minecraftforge.fml.client.config.GuiUtils.drawHoveringText(GuiUtils.java:409)
	at elec332.core.inventory.tooltip.ToolTip.renderTooltip(ToolTip.java:55)
	at elec332.core.inventory.window.Window.drawScreenPost(Window.java:419)
	at elec332.craftingtableiv.inventory.WindowCraftingTableIV.drawScreenPost(WindowCraftingTableIV.java:414)
	at elec332.core.inventory.window.WindowGui.func_73863_a(WindowGui.java:98)
	at net.minecraftforge.client.ForgeHooksClient.drawScreen(ForgeHooksClient.java:396)
	at sun.reflect.GeneratedMethodAccessor42.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.optifine.reflect.Reflector.callVoid(Reflector.java:660)
	at net.minecraft.client.renderer.EntityRenderer.func_181560_a(EntityRenderer.java:1456)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1119)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:398)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
```
