### ISSUE TITLE
Kicks client from server 1.12.2

### ISSUE THREAD

**Issue by xxxLEOPARDxxx** [Elecs-Mods/CraftingTable-IV#80]
[crash-2019-03-14_01.26.41-client.txt](https://github.com/Elecs-Mods/CraftingTable-IV/files/2963912/crash-2019-03-14_01.26.41-client.txt)

Server

[01:26:43] [Netty Server IO #2/ERROR] [FML]: NetworkDispatcher exception
java.io.IOException: Удаленный хост принудительно разорвал существующее подключение
        at sun.nio.ch.SocketDispatcher.read0(Native Method) ~[?:1.8.0_201]
        at sun.nio.ch.SocketDispatcher.read(Unknown Source) ~[?:1.8.0_201]
        at sun.nio.ch.IOUtil.readIntoNativeBuffer(Unknown Source) ~[?:1.8.0_201]
        at sun.nio.ch.IOUtil.read(Unknown Source) ~[?:1.8.0_201]
        at sun.nio.ch.SocketChannelImpl.read(Unknown Source) ~[?:1.8.0_201]
        at io.netty.buffer.PooledUnsafeDirectByteBuf.setBytes(PooledUnsafeDirectByteBuf.java:288) ~[PooledUnsafeDirectByteBuf.class:?]
        at io.netty.buffer.AbstractByteBuf.writeBytes(AbstractByteBuf.java:1100) ~[AbstractByteBuf.class:?]
        at io.netty.channel.socket.nio.NioSocketChannel.doReadBytes(NioSocketChannel.java:372) ~[NioSocketChannel.class:?]
        at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:123) [AbstractNioByteChannel$NioByteUnsafe.class:?]
        at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:624) [NioEventLoop.class:?]
        at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:559) [NioEventLoop.class:?]
        at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:476) [NioEventLoop.class:?]
        at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:438) [NioEventLoop.class:?]
        at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:858) [SingleThreadEventExecutor$5.class:?]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_201]

**Comment by Elec332** [comment]
This has been fixed in the latest version of ElecCore:
https://www.curseforge.com/minecraft/mc-mods/eleccore/files/2853959
