### ISSUE TITLE
Game Freezes w/ the Ultimate Car Mod

### ISSUE THREAD

**Issue by WenXin20** [Elecs-Mods/CraftingTable-IV#89]
`Minecraft v1.14.4`
`Forge v28.1.109`
`ElecCore v2.0.25-beta`
`Crafting Table IV v1.6.119`
`Ultimate Cars v2.0.23`

If the [Ultimate Car Mod](https://www.curseforge.com/minecraft/mc-mods/ultimate-car-mod) is installed, the game will freeze, but not crash, as soon as the Crafting Table IV is placed.

[Full Log](https://gist.github.com/WenXin20/6b30f6365e3d416b6306ce6ae71822a8) (Error starts at `[13:19:31]`)

```
java.lang.NullPointerException
	at de.maxhenkel.car.events.CapabilityEvents.capabilityAttachTileEntity(CapabilityEvents.java:25)
	at net.minecraftforge.eventbus.ASMEventHandler_440_CapabilityEvents_capabilityAttachTileEntity_AttachCapabilitiesEvent.invoke(.dynamic)
	at net.minecraftforge.eventbus.ASMEventHandler.invoke(ASMEventHandler.java:80)
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:258)
	at net.minecraftforge.event.ForgeEventFactory.gatherCapabilities(ForgeEventFactory.java:557)
	at net.minecraftforge.event.ForgeEventFactory.gatherCapabilities(ForgeEventFactory.java:551)
	at net.minecraftforge.common.capabilities.CapabilityProvider.gatherCapabilities(CapabilityProvider.java:48)
	at net.minecraftforge.common.capabilities.CapabilityProvider.gatherCapabilities(CapabilityProvider.java:44)
	at net.minecraft.tileentity.TileEntity.<init>(TileEntity.java:34)
	at elec332.core.tile.AbstractTileEntity.<init>(AbstractTileEntity.java:38)
	at elec332.craftingtableiv.tileentity.TileEntityCraftingTableIV.<init>(TileEntityCraftingTableIV.java:25)
	at elec332.craftingtableiv.blocks.BlockCraftingTableIV.createTileEntity(BlockCraftingTableIV.java:134)
	at net.minecraftforge.common.extensions.IForgeBlockState.createTileEntity(IForgeBlockState.java:149)
	at net.minecraft.world.chunk.Chunk.func_177436_a(Chunk.java:288)
	at net.minecraft.world.World.func_180501_a(World.java:192)
	at net.minecraft.client.world.ClientWorld.func_180501_a(ClientWorld.java:722)
	at net.minecraft.item.BlockItem.func_195941_b(BlockItem.java:146)
	at net.minecraft.item.BlockItem.func_195942_a(BlockItem.java:54)
	at net.minecraft.item.BlockItem.func_195939_a(BlockItem.java:39)
	at net.minecraft.item.ItemStack.lambda$onItemUse$0(ItemStack.java:163)
	at net.minecraft.item.ItemStack$$Lambda$7125/1629279161.apply(Unknown Source)
	at net.minecraft.item.ItemStack.onItemUse(ItemStack.java:178)
	at net.minecraft.item.ItemStack.func_196084_a(ItemStack.java:163)
	at net.minecraft.client.multiplayer.PlayerController.func_217292_a(PlayerController.java:292)
	at net.optifine.override.PlayerControllerOF.func_217292_a(PlayerControllerOF.java:98)
	at net.minecraft.client.Minecraft.func_147121_ag(Minecraft.java:1236)
	at net.minecraft.client.Minecraft.func_184117_aA(Minecraft.java:1488)
	at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:1321)
	at net.minecraft.client.Minecraft.func_195542_b(Minecraft.java:869)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:384)
	at net.minecraft.client.main.Main.main(SourceFile:155)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraftforge.fml.loading.FMLClientLaunchProvider.lambda$launchService$0(FMLClientLaunchProvider.java:56)
	at net.minecraftforge.fml.loading.FMLClientLaunchProvider$$Lambda$419/159860059.call(Unknown Source)
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37)
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:54)
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:72)
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:81)
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:65)
```

**Comment by Elec332** [comment]
Ill leave this open for now, but please report this to the Ultimate Car Mod.
I have no idea if it's on their end or mine, but I cannot verify this as their project is closed source.

**Comment by WenXin20** [comment]
Alright, thanks!

**Comment by WenXin20** [comment]
Link to issue [here](https://www.curseforge.com/minecraft/mc-mods/ultimate-car-mod/issues/92)

**Comment by WenXin20** [comment]
Fixed on their end!
