### ISSUE TITLE
Incompatibility with IC2 Classic

### ISSUE THREAD

**Issue by Chocohead** [Elecs-Mods/CraftingTable-IV#9]
The game loads fine, but upon trying to load a world, the game crashes:

Description: Exception in server tick loop

cpw.mods.fml.common.LoaderException: java.lang.NoSuchFieldError: masks
    at cpw.mods.fml.common.LoadController.transition(LoadController.java:163)
    at cpw.mods.fml.common.Loader.serverStarted(Loader.java:803)
    at cpw.mods.fml.common.FMLCommonHandler.handleServerStarted(FMLCommonHandler.java:283)
    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:389)
    at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685)
Caused by: java.lang.NoSuchFieldError: masks
    at elec332.craftingtableiv.handler.Compat$1.getIngredients(Compat.java:68)
    at elec332.craftingtableiv.handler.Compat$1.getIngredients(Compat.java:62)
    at elec332.craftingtableiv.api.AbstractRecipeHandler.getWrappedRecipe(AbstractRecipeHandler.java:13)
    at elec332.craftingtableiv.handler.CraftingHandler.getWrappedRecipe(CraftingHandler.java:352)
    at elec332.craftingtableiv.handler.CraftingHandler.InitRecipes(CraftingHandler.java:286)
    at elec332.craftingtableiv.CraftingTableIV.loadRecipes(CraftingTableIV.java:124)
    at elec332.craftingtableiv.CraftingTableIV.serverStarted(CraftingTableIV.java:113)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
    at java.lang.reflect.Method.invoke(Unknown Source)
    at cpw.mods.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:532)
    at sun.reflect.GeneratedMethodAccessor3.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
    at java.lang.reflect.Method.invoke(Unknown Source)
    at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
    at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
    at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
    at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
    at com.google.common.eventbus.EventBus.post(EventBus.java:275)
    at cpw.mods.fml.common.LoadController.sendEventToModContainer(LoadController.java:212)
    at cpw.mods.fml.common.LoadController.propogateStateMessage(LoadController.java:190)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
    at java.lang.reflect.Method.invoke(Unknown Source)
    at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
    at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
    at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
    at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
    at com.google.common.eventbus.EventBus.post(EventBus.java:275)
    at cpw.mods.fml.common.LoadController.distributeStateMessage(LoadController.java:119)
    at cpw.mods.fml.common.Loader.serverStarted(Loader.java:802)
    ... 3 more

**Comment by Elec332** [comment]
The problem is, the mod uses the same ModID as IC2, and even uses the same class names, and they change stuff in that. And besides the point is they are even allowed to change and upload a changed IC2 version, I think that it should have another mod-ID that normal IC2, because this makes compatibilty extremely difficult.

Ill look into this, anywhere where I can download this mod?

**Comment by Chocohead** [comment]
Speiger kept it the same so that addons could work with it. The downloads and API are at https://github.com/TinyModularThings/IC2Classic/releases.

xbony detects it for Nuclear Control here: https://github.com/xbony2/Nuclear-Control/blob/master/src/main/java/shedar/mods/ic2/nuclearcontrol/crossmod/ic2classic/CrossIndustrialCraft2Classic.java

**Comment by Elec332** [comment]
Aha, so there are 2 versions of IC2 Classic floating around? Interesting.

Ill look into this.

**Comment by Speiger** [comment]
@Elec332 well yeah it is the recipe class thing. You simply should make a differend handler for a differend IC2 Type. IC2 Classic has also a ModID for detection so that you can see the differences without installing the classic API (If you do not want to have it in your modpack)

**Comment by Elec332** [comment]
Yea, but my compat handler works on class names, so Ill have to not-register the normal IC2 stuff when a classic version is loaded

**Comment by Speiger** [comment]
@Elec332 no thats not true. You simply have to ask differend things. Thats it...
IC2 Classic Dev versions are aviable so you can read the sourcecode if you want to :3
